apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-k8s-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Testingbyme0011/2-ArgoCD-Multi-Env.git
    targetRevision: HEAD
    path: Staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
