apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-rollout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Testingbyme0011/5-ArgoCD-Gitops-Argo-Rollouts.git
    targetRevision: HEAD
    path: rollout-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
