apiVersion: v1
kind: Namespace
metadata:
  name: pss-demo
  labels:
    pod-security.kubernetes.io/enforce: restricted
---
# Violating pod (privileged) – should be blocked by admission
apiVersion: v1
kind: Pod
metadata:
  name: naughty
  namespace: pss-demo
spec:
  containers:
  - name: c
    image: busybox
    command: ["sh","-c","sleep 3600"]
    securityContext:
      privileged: true
---
# Compliant pod
apiVersion: v1
kind: Pod
metadata:
  name: nice
  namespace: pss-demo
spec:
  containers:
  - name: c
    image: busybox
    command: ["sh","-c","sleep 3600"]
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      capabilities:
        drop: ["ALL"]
