apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v1
spec:
  replicas: 2
  selector: { matchLabels: { app: web, version: v1 } }
  template:
    metadata: { labels: { app: web, version: v1 } }
    spec:
      containers:
      - name: web
        image: ghcr.io/k8s-demos-mini/web:1.0
        ports: [{ containerPort: 8080 }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
spec:
  replicas: 2
  selector: { matchLabels: { app: web, version: v2 } }
  template:
    metadata: { labels: { app: web, version: v2 } }
    spec:
      containers:
      - name: web
        image: ghcr.io/k8s-demos-mini/web:2.0
        ports: [{ containerPort: 8080 }]
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector: { app: web, version: v1 }   # <-- start on v1
  ports: [{ port: 80, targetPort: 8080 }]
  type: NodePort
