apiVersion: v1
kind: Namespace
metadata:
  name: shop
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: shop
data:
  DB_HOST: mysql
  DB_NAME: shopdb
  DB_USER: shopuser
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: shop
type: Opaque
stringData:
  DB_PASSWORD: "supersafe"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: shop
spec:
  clusterIP: None  # headless for StatefulSet
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: shop
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: shop
spec:
  serviceName: mysql
  selector:
    matchLabels: { app: mysql }
  replicas: 1
  template:
    metadata:
      labels: { app: mysql }
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          value: rootpass
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        readinessProbe:
          exec: { command: ["sh","-c","mysqladmin ping -h 127.0.0.1 -uroot -prootpass"] }
          initialDelaySeconds: 15
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata: { name: data }
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests: { storage: 5Gi }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: shop
spec:
  replicas: 2
  selector: { matchLabels: { app: backend } }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
      - name: app
        # Tiny Flask API that talks to MySQL
        image: ghcr.io/k8s-demos-mini/flask-mysql-demo:1.0
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secrets
              key: DB_PASSWORD    
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet: { path: /healthz, port: 5000 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /livez, port: 5000 }
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: shop
spec:
  selector: { app: backend }
  ports:
  - port: 80
    targetPort: 5000
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shop
spec:
  replicas: 2
  selector: { matchLabels: { app: frontend } }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
      - name: nginx
        image: nginx:1.27-alpine
        ports: [{ containerPort: 80 }]
        volumeMounts:
        - name: cfg
          mountPath: /etc/nginx/conf.d
        readinessProbe:
          httpGet: { path: /, port: 80 }
          initialDelaySeconds: 5
      volumes:
      - name: cfg
        configMap:
          name: fe-nginx
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-nginx
  namespace: shop
data:
  default.conf: |
    upstream backend {
      server backend.shop.svc.cluster.local:80;
    }
    server {
      listen 80;
      location / {
        proxy_pass http://backend;
    } }
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: shop
spec:
  type: NodePort
  selector: { app: frontend }
  ports:
  - port: 80
    targetPort: 80




#91197/flask-app:1.0