apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Testingbyme0011/4-ArgoCD-Gitops-Multi-Cluster.git
    targetRevision: HEAD
    path: backend
  destination:
    server: https://127.0.0.1:38181   # use `argocd cluster list` to copy
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
